spring:
    profiles:
        active:
            - dev
---
spring:
    profiles: dev #开发环境
    applications: 
        name: microservicecloud-config-dev-1
---
spring:
    profiles: test #测试环境
    applications: 
        name microservicecloud-config-test
    
