spring:
    profiles:
        active:
            - dev
---
server:
    port: 9527
spring:
    profiles: dev
    application:
        name: microservicecloud-config-zuul-client9527
    cloud:
        gateway:
            routes:
                id: path_route
                uri: http://localhost:8000
            order: 0
            predicates:
                - Path=/**
            filters:
                - StripPrefix=1
        discovery:
            locator:
                enabled: true
                lowerCaseServiceId: true 
eureka:
    client:
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
