spring:
    profiles:
        active:
            - dev
---
server:
    port: 9527
spring:
    profiles: dev
    application:
        name: microservicecloud-config-zuul-client9527
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
eureka:
    client:
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
        healthcheck:
            enabled: true #健康检查（需要spring-boot-starter-actuator依赖）
    instance:
        lease-expiration-duration-in-seconds: 10 # 续约更新时间间隔（默认30秒）
        lease-renewal-interval-in-seconds: 10 # 续约到期时间（默认90秒）
      
zuul:
  routes:
    provider-server8001:
        path: /dept1/**
        strip-prefix: true
        url: http://provider8001:8001
    provider-server8002:
        path: /dept2/**
        strip-prefix: true
        url: http://provider8002:8002    
  ignored-services: "*"
  prefix: /api
