server:
  port: 9000
spring:
  profiles: dev
  application:
    name: microservicecloud-config-feign-client9000
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
  zipkin:
    base-url: http://zipkin-9003.com:9003
  boot:
        admin:
          client:
            url: http://admin-9004.com:9004
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
feign:
  httpclient:
    connection-timeout: 30000
  hystrix:
    enabled: true