server:
    port: 9001
spring:
  application:
    name: microservicecloud-config-ribbon-client9001
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest    
  boot:
        admin:
          client:
            url: http://localhost:9004
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
