server:
    port: 9003
spring:
    profiles: dev
    application:
        name: microservicecloud-config-zipkin-client9003
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/